# Setup
title:        Sekorm+
tagline:      GitHub Pages for Sekorm Shared Information
url:          "http://chen-node.com/Sekorm"
baseurl:      "/Sekorm"
paginate:     1

# About/contact
author:
  name:       Chen Xie
  url:        https://github.com/neilChenXie

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
